# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL is set in hugo.toml
locale = "en"
defaultContentLanguage = "en"

title = "Fumiya Oura"

enableRobotsTXT = true

summaryLength = 0
