[en]
  label = "English"
  weight = 1
  title = "Fumiya Oura"

  [en.params.author]
    name = "Fumiya Oura"
    headline = "Experimental nuclear physicist"
    bio = "JAEA / Advanced Science Research Center"

[ja]
  label = "日本語"
  weight = 2
  title = "大浦 文也"

  [ja.params.author]
    name = "大浦 文也"
    headline = "原子核実験物理の研究者"
    bio = "日本原子力研究開発機構 先端基礎研究センター"
