# -- Main Menu (Japanese) --

[[main]]
  name = "経歴"
  pageRef = "about"
  weight = 10

[[main]]
  name = "研究"
  pageRef = "research"
  weight = 20

[[main]]
  name = "論文"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "発表"
  pageRef = "talks"
  weight = 40

[[main]]
  name = "研究費"
  pageRef = "grants"
  weight = 50

[[main]]
  name = "ニュース"
  pageRef = "news"
  weight = 60

# Hidden until the simulators are ready to show.
# [[main]]
#   name = "ソフトウェア"
#   pageRef = "software"
#   weight = 70

[[main]]
  name = "お問い合わせ"
  pageRef = "links"
  weight = 80

# -- Footer Menu --

[[footer]]
  name = "共同研究者"
  pageRef = "collaborators"
  weight = 10

[[footer]]
  name = "ギャラリー"
  pageRef = "gallery"
  weight = 20

[[footer]]
  name = "オフトピック"
  pageRef = "offtopic"
  weight = 30
